// Manual BOM compare — the contractor-private worksheet matcher
// (mirror of app.js compareManualBom; compare-only, never feeds totals)
const { normalizeBomName, compareManualBom, parseMaterialListText } = require('../client/dist/js/bom');

describe('parseMaterialListText (compare worksheet paste)', () => {
  test('plain "name x20" and "name qty price" lines', () => {
    const r = parseMaterialListText('4x4x8 posts x20\npickets 300 2.38\nconcrete bags 45');
    expect(r.rows).toEqual([
      { name: '4x4x8 posts', qty: 20, unitCost: 0 },
      { name: 'pickets', qty: 300, unitCost: 2.38 },
      { name: 'concrete bags', qty: 45, unitCost: 0 }
    ]);
    expect(r.skipped).toBe(0);
  });

  test('CSV with price and the app\'s own export shape (name,qty,unit,cost,total)', () => {
    const r = parseMaterialListText('2x4x16 rails, 29, 13.88\n4x4x8 line posts,18,ea,9.98,179.64');
    expect(r.rows[0]).toEqual({ name: '2x4x16 rails', qty: 29, unitCost: 13.88 });
    expect(r.rows[1]).toEqual({ name: '4x4x8 line posts', qty: 18, unitCost: 9.98 });
  });

  test('markdown table with header and separator rows', () => {
    const r = parseMaterialListText([
      '| Item | Qty | Price |',
      '|------|----:|------:|',
      '| dog-ear pickets | 323 | $2.38 |',
      '| post caps | 20 | 7.98 |'
    ].join('\n'));
    expect(r.rows).toEqual([
      { name: 'dog-ear pickets', qty: 323, unitCost: 2.38 },
      { name: 'post caps', qty: 20, unitCost: 7.98 }
    ]);
    expect(r.skipped).toBe(0);
  });

  test('round-trips the app\'s own clipboard export (qty-first lines)', () => {
    const clip = [
      'Material List',
      'Customer: Test',
      'Date: 6/11/2026',
      '',
      '18 4x4x8 PT line posts',
      '2 4x4x8 PT corner/end posts',
      '29 2x4x16 PT rails',
      '323 1x6x6 dog ear PT pickets',
      '114 Rail brackets',
      '20 Post caps',
      '40 50lb concrete bags',
      '22 Exterior deck screws (box)',
      '',
      'Generated by FenceTrace'
    ].join('\n');
    const r = parseMaterialListText(clip);
    expect(r.rows.length).toBe(8);
    expect(r.rows[0]).toEqual({ name: '4x4x8 PT line posts', qty: 18, unitCost: 0 });
    expect(r.rows[6]).toEqual({ name: '50lb concrete bags', qty: 40, unitCost: 0 });
    expect(r.skipped).toBe(0); // prologue/footer lines are not errors
  });

  test('section headers from multi-section exports are ignored', () => {
    const r = parseMaterialListText('--- Section 1: Wood 6ft — 120 ft ---\n18 4x4x8 PT line posts');
    expect(r.rows.length).toBe(1);
    expect(r.skipped).toBe(0);
  });

  test('markdown table pasted without leading pipe on the first row', () => {
    const r = parseMaterialListText('4x4x8 line posts      | 18           | 9.98    | 179.64     |\n| Post caps             | 20           | 7.98    | 159.60      |');
    expect(r.rows).toEqual([
      { name: '4x4x8 line posts', qty: 18, unitCost: 9.98 },
      { name: 'Post caps', qty: 20, unitCost: 7.98 }
    ]);
  });

  test('caps at 50 rows and validates ranges', () => {
    const lines = [];
    for (let i = 0; i < 60; i++) lines.push('item' + i + ' 5');
    const r = parseMaterialListText(lines.join('\n'));
    expect(r.rows.length).toBe(50);
    const bad = parseMaterialListText('thing 50000\nother 5 2000000');
    expect(bad.rows.length).toBe(0);
    expect(bad.skipped).toBe(2);
  });

  test('empty and prose input degrade safely', () => {
    expect(parseMaterialListText('').rows).toEqual([]);
    expect(parseMaterialListText('no numbers here').rows).toEqual([]);
    expect(parseMaterialListText(null).rows).toEqual([]);
  });
});

describe('normalizeBomName', () => {
  test('lowercases, strips punctuation, splits digit/letter boundaries', () => {
    expect(normalizeBomName('4x4x8 PT  Posts!')).toBe('4 x 4 x 8 pt posts');
    expect(normalizeBomName('50lb concrete bags')).toBe('50 lb concrete bags');
    expect(normalizeBomName('  Rail-Brackets (galv.) ')).toBe('rail brackets galv');
    expect(normalizeBomName(null)).toBe('');
  });
});

describe('compareManualBom', () => {
  const computed = [
    { name: 'Section 1: Wood 6ft — 120 ft', qty: 0, isHeader: true },
    { name: '4x4x8 PT posts', qty: 19, unitCost: 16, total: 304 },
    { name: '2x4x16 rails', qty: 23, unitCost: 9, total: 207 },
    { name: 'Concrete bags (50lb)', qty: 38, unitCost: 6, total: 228 }
  ];

  test('exact name match (case/punctuation-insensitive) with qty delta', () => {
    const r = compareManualBom([{ name: '4X4X8 pt POSTS', qty: 17, unitCost: 15 }], computed);
    expect(r.rows[0].countedName).toBe('4x4x8 PT posts');
    expect(r.rows[0].countedQty).toBe(19);
    expect(r.rows[0].qtyDelta).toBe(2); // FenceTrace counts 2 more
  });

  test('substring match when no exact match', () => {
    const r = compareManualBom([{ name: 'concrete bags', qty: 38 }], computed);
    expect(r.rows[0].countedName).toBe('Concrete bags (50lb)');
    expect(r.rows[0].qtyDelta).toBe(0);
  });

  test('headers are never matched', () => {
    const r = compareManualBom([{ name: 'Section 1', qty: 1 }], computed);
    expect(r.rows[0].countedName).toBeNull();
  });

  test('exact match wins even when an earlier row would substring-claim it', () => {
    const r = compareManualBom(
      [{ name: 'posts', qty: 5 }, { name: '4x4x8 PT posts', qty: 17 }],
      computed
    );
    expect(r.rows[1].countedName).toBe('4x4x8 PT posts');
    expect(r.rows[0].countedName).toBeNull();
  });

  test('a computed item is matched at most once', () => {
    const r = compareManualBom(
      [{ name: '4x4x8 PT posts', qty: 10 }, { name: '4x4x8 posts', qty: 5 }],
      computed
    );
    expect(r.rows[0].countedName).toBe('4x4x8 PT posts');
    expect(r.rows[1].countedName).toBeNull();
  });

  test('short names (<3 chars) only match exactly, not by substring', () => {
    const r = compareManualBom([{ name: 'pt', qty: 1 }], computed);
    expect(r.rows[0].countedName).toBeNull();
  });

  test('digit-unit and plural variants match (the QA-table names)', () => {
    const realBom = [
      { name: '4x4x8 PT line posts', qty: 18 },
      { name: '1x6x6 dog ear PT pickets', qty: 323 },
      { name: '50lb concrete bags', qty: 40 },
      { name: 'Exterior deck screws (box)', qty: 22 }
    ];
    const r = compareManualBom([
      { name: '50 lb concrete bags', qty: 40 },
      { name: 'Screw boxes', qty: 22 },
      { name: 'pickets', qty: 300 },
      { name: 'line posts', qty: 18 }
    ], realBom);
    expect(r.rows[0].countedName).toBe('50lb concrete bags');
    expect(r.rows[0].qtyDelta).toBe(0);
    expect(r.rows[1].countedName).toBe('Exterior deck screws (box)');
    expect(r.rows[2].countedName).toBe('1x6x6 dog ear PT pickets');
    expect(r.rows[2].qtyDelta).toBe(23);
    expect(r.rows[3].countedName).toBe('4x4x8 PT line posts');
    expect(r.unmatchedComputed).toEqual([]);
  });

  test('unmatched computed items are listed', () => {
    const r = compareManualBom([{ name: '4x4x8 PT posts', qty: 19 }], computed);
    expect(r.unmatchedComputed).toEqual([
      { name: '2x4x16 rails', qty: 23 },
      { name: 'Concrete bags (50lb)', qty: 38 }
    ]);
  });

  test('manualTotal sums qty*unitCost with cent rounding', () => {
    const r = compareManualBom(
      [{ name: 'a-item', qty: 3, unitCost: 1.335 }, { name: 'b-item', qty: 1 }],
      []
    );
    expect(r.manualTotal).toBe(4.01); // 4.005 rounded
    expect(r.rows[1].unitCost).toBe(0);
  });

  test('empty and missing inputs degrade safely', () => {
    expect(compareManualBom([], computed).rows).toEqual([]);
    expect(compareManualBom(null, null)).toEqual({ rows: [], manualTotal: 0, unmatchedComputed: [] });
  });
});
